modules/weko-search-ui/tests/test_utils.py
modules/weko-search-ui/weko_search_ui/admin.py
modules/weko-search-ui/weko_search_ui/config.py
modules/weko-search-ui/weko_search_ui/rest.py
modules/weko-search-ui/weko_search_ui/utils.py

コード変更箇所の概要
* 基本的にはcopy.deepcopy(data)をpickle.loads(pickle.dumps(data,-1))に変換
* DefaultOrderedDict.__deepcopy__　に関連する処理の変更メソッド
* __deepcopy__の戻り値は、self.items()をリスト化したオブジェクトをpickle化する処理を行った後、得られる値とした
* pickle.loads(pickle.dumps(list(self.items())メソッド__reduce__の5つ目の戻り値を、イテラブルオブジェクトiter(self.items())に変更した
　　　上記2点の変更を両方とも加えた場合、テスト結果がFAILED→PASSEDになることを確認
* メソッドtest_read_stats_csvの仕様変更に合わせたテストコードの修正
* 仕様変更に合わせ引数を追加
* 比較対象辞書のkey名が異なっていたため、テストコードの修正により、発生していたAssertion Errorを解消　　　
　　上記2点の変更を両方とも加えた場合、仕様変更後のコードでテスト結果がFAILED→PASSEDになることを確認
以上です。コードレビューをよろしくお願いいたします。

replace deepcopy with pickle / weko-search-ui

---

modules/weko-records-ui/tests/test_views.py
modules/weko-records-ui/weko_records_ui/static/js/weko_records_ui/detail.js
modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/_macros.html
modules/weko-records-ui/weko_records_ui/views.py

制限公開アイテムが「提供方法：ワークフロー」に「利用規約のみ」、「提供方法：ロール」に「非ログインユーザー」が設定されている場合、
非ログインユーザがそのアイテムに申請をした時のメールアドレス入力を省略してDLできるようにしました。
modules/weko-records-ui/weko_records_ui/static/js/weko_records_ui/detail.js
・利用規約のみかつ非ログインユーザである場合にurl:/activity/init-guestにダウンロードリクエストを投げるメソッドterms_only_guest_downloadを追加しました。L77-115
・利用規約のみかつ非ログインユーザである場合に利用規約に同意した時にDLできるようにしました。L218-230
・利用規約のみで利用規約を設定していない場合にも非ログインユーザがDLをそのままできるようにしました。 L243-259
modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/_macros.html
・modules/weko-records-ui/weko_records_ui/views.pyによって渡される変数を保持する処理を加えました。
modules/weko-records-ui/weko_records_ui/views.py
・def get_workflow_detailにて返り値にワークフローが利用規約のみかどうかの変数を追加しました。

Feature/jgss pre dev 3 (1)

---

modules/weko-deposit/tests/test_receivers.py

elasticsearch修正に伴う単体テストコード修正です。
・weko-deposit/receivers.pyのappend_file_contentメソッド

elasticsearch修正に伴う単体テストの追加です。

---

modules/weko-search-ui/weko_search_ui/templates/weko_search_ui/body_facet_search.html

対象のバグ
- 『トップ』ボタン押下後のTOP画面表示でファセット検索項目チェックボックスの条件項目が表示されない。
対処内容
- defer属性を付与して、jsの実行タイミングを変更しました

パフォーマンス改善/バグ修正/facet_search.jsの実行タイミングの変更

---

modules/weko-theme/weko_theme/static/js/weko_theme/top_page.js

バグ内容
- 詳細検索→簡易検索を行った場合、詳細検索のパラメータ（title、creator、text1、date_range1_from、date_range1_to）が消える
原因
- ファセット検索のパラメータを取得する関数getFacetParameterが本来の機能を実現できていないことによる影響
- URLから削除する詳細検索のキーを網羅できていない状況
- 正しくファセット検索用のパラメータだけを返すようにしてしまうと、既存の仕様と大きく変わってしまうため(詳細→簡易を行った際に詳細検索のパラメータが全て消えてしまう)、暫定対応として、簡易検索以外のパラメータを全て返すこととする
改修内容
- URLから削除する対象となっていたキー　'title', 'creator', 'date_range1_from', 'date_range1_to', text*　を削除対象外とした

パフォーマンス改善/バグ/詳細検索のクエリパラメータ維持

---

modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
modules/weko-theme/weko_theme/static/js/weko_theme/top_page.js

コミュニティ機能を使用している状態のことを考慮できていなかったため、元の仕様に戻しました
以下の場合に詳細検索使用中と判断されてしまっていた
/search?page=1&size=20&sort=controlnumber&search_type=0&q=test&community=test1

パフォーマンス改善/バグ修正/コミュニティを考慮した詳細検索エリア

---

modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/detail.html
modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/file_details.html
modules/weko-search-ui/weko_search_ui/templates/weko_search_ui/admin/item_management_display.html
modules/weko-search-ui/weko_search_ui/templates/weko_search_ui/search.html
modules/weko-theme/weko_theme/templates/weko_theme/admin/item_management_display.html
modules/weko-theme/weko_theme/templates/weko_theme/frontpage.html

結合テストのバグ修正
バグ管理番号：P-002
- 詳細検索条件の項目数が2の時、詳細検索エリアは開かれるが、条件が保持されない
- 詳細検索情報を保持する処理を行うsearch_detail.jsと、詳細検索エリアの開閉を制御するtop_page.jsの実行タイミングによって、生成されているクエリパラメータに違いがあった
- 詳細検索の使用状況の判断は、各jsとも、クエリパラメータの数が6よりも大きいか否かで判断している
- 詳細検索項目を　タイトル、著者名　で検索した場合、各jsで取得できるクエリパラメータは以下の様になり、詳細検索エリアは開いているが、詳細検索条件は取得できていない状態になっていた（search_detail.jsには　size　がない）
top_page.js　：　page,size,sort,search_type,q,title,creator
search_detail.js　：　page,search_type,q,title,creator,sort
- search_detail.jsを呼び出すhtmlテンプレートにdefer属性を付与して実行順序を変更することで対応した

パフォーマンス改善/結合テストバグ修正/P-002

---

modules/weko-index-tree/tests/test_api.py
modules/weko-index-tree/weko_index_tree/api.py

移行ツール側でWEKO2でのログ記録日におけるインデックスの公開状態を取得するため、`Indexes.get_public_indexes_list`メソッドで日付の指定ができるよう修正しました。
また、NII_WEKO3-174 で課題としている既存ログにオープンアクセス判定結果を付与するマイグレーション作業の際にもこのメソッドが使用できるかと思います。

NII_WEKO3-86 ＜実装＞4. 【移行ツール】[定型レポート] 「インデックスアクセス回数」と各レポートの出力項目「登録インデックス名」が表示されない

---

modules/weko-index-tree/tests/data/mappings/item-v1.0.0.json

21663b02b23ed467fea275a491d187a1acfc3ddc
の修正のみ
マージ時に複数作業者の変更が入っており、想定通りの挙動をしていなかった

weko-index-tree マージ問題対する修正

---

modules/invenio-indexer/tox.ini

invenio-indexerでカバレッジ取得できない問題　解消
フォルダパス指定が誤っていたものを修正

invenio-indexerでカバレッジ取得できない問題　解消

---

modules/weko-records-ui/tests/test_models.py
modules/weko-records-ui/weko_records_ui/fd.py
modules/weko-records-ui/weko_records_ui/models.py
modules/weko-records-ui/weko_records_ui/utils.py

シークレットURLとワンタイムURLのモデル定義の変更
以下の変更を加えました。
- FileSecretDownloadとFileOnetimeDownloadクラスのカラム定義を変更
- CHECK制約を付与
- 削除API用のメソッドを追加
- 両クラスで共通するメソッドをmixinクラスに統合
- 二つのクラス間で共通する処理が複数あったため、mixinクラスに統合したが問題がないか
- コーディング規約のGoogle Styleに合わせ、docstringを大幅に変更したが問題がないか
- DL回数のカウントアップについて、既存のクラスメソッドではなく新規に作成したインスタンスメソッドを用いる方針だが問題がないか

W2024-23 | Change models  for URL download

---

modules/weko-records-ui/tests/test_fd.py
modules/weko-records-ui/tests/test_models.py
modules/weko-records-ui/tests/test_utils.py
modules/weko-records-ui/tests/test_views.py
modules/weko-records-ui/weko_records_ui/config.py
modules/weko-records-ui/weko_records_ui/fd.py
modules/weko-records-ui/weko_records_ui/models.py
modules/weko-records-ui/weko_records_ui/utils.py
modules/weko-records-ui/weko_records_ui/views.py

シークレットURL・ワンタイムURLのコピー機能のエンドポイントとバックエンド処理を追加
- config.pyにコピー用のエンドポイントを追加
- views.pyにコピー用の関数を追加
- utils.pyにワンタイムURLの編集権限確認メソッドを追加
- ワンタイムURLのみ、代理投稿者へ権限を付与しない
ダウンロード履歴の保存の記述を一部修正

W2024-23 | Add copy endpoint to download URL feature

---

modules/weko-admin/weko_admin/static/js/weko_admin/facet_search_admin.js
nginx/weko-ams.conf

・デモ環境用のnginxの設定ファイルでリクエストメールのAPIを使用可能なIPアドレスを制限する
・デモ環境用のnginxの設定ファイルでプレビュー機能が使えない不具合を修正
・admin画面のファセット検索設定画面の不具合を修正

restrict requestmail api

---

modules/invenio-communities/invenio_communities/alembic/1b352b00f1ed_add_columns.py
modules/invenio-communities/invenio_communities/models.py

invenio-communities に alembic を追加した影響で、既存のマイグレーションと競合が発生し、
両方の修正を適用できない状態になっていました。
本PRでは、down_revision を適切に修正し、マイグレーションの適用順序を正しくしました。

invenio-communitiesのalembicの整理

---

modules/weko-admin/weko_admin/alembic/030be6fdaa51_add_server_deafult_to_repository_id.py
modules/weko-records/weko_records/alembic/4d2556236060_add_server_deafult_to_repository_id.py

このプルリクエストでは、以下の変更を行いました：
- repository_id カラムに server_default を追加
- サブリポジトリ管理機能で追加したカラムの"repository_id"にserver_defaultを追加するマイグレーションスクリプトを追加しました。
- これにより、既存データには'Root Index'が設定されるようになりました。
- feedback_email_setting テーブルの repository_id カラムに server_default を追加。
- feedback_mail_history テーブルの repository_id カラムに server_default を追加。
- stats_email_address テーブルの repository_id カラムに server_default を追加。
- feedback_mail_list テーブルの repository_id カラムに server_default を追加。
- sitelicense_info テーブルの repository_id カラムに server_default を追加。
データベースマイグレーションを実行した後、各テーブルで repository_id に対してデフォルト値が正しく設定されることを確認しました。
ご確認のほど、よろしくお願い致します。

repository_id に server_default を追加

---

modules/invenio-communities/invenio_communities/admin.py
modules/invenio-communities/tests/test_admin.py
scripts/demo/defaultworkflow.sql

このPRでは、以下の2つの変更を含みます：
CommunityModelViewのcreate_viewのDB登録処理を修正しました。
また、修正箇所のテストコードを修正、実施しました。
ワークフローにカラムを追加した影響で初期データが登録できなかったため、defaultworkflow.sqlを修正しました。
以上、よろしくお願いします。

コミュニティ新規作成時のエラー修正 & 初期データ登録修正

---

modules/weko-search-ui/weko_search_ui/utils.py

weko_search_uiのexport_all()を修正しました。
index_id_listがNoneの場合にシステム管理者としてすべてのアイテムを取得する処理になっていなかったので修正しました。

export_allのindex_id_listの処理を修正

---

modules/invenio-communities/invenio_communities/admin.py

コミュニティ管理者にコミュニティ作成画面を表示しないように修正した。
コミュニティ管理画面には作成タブが表示されないが、URLから直接コミュニティ作成画面に遷移できたため、
制限し、「権限が必要です」と表示するように修正した。

コミュニティ管理者のコミュニティ作成画面を制限

---

modules/invenio-communities/invenio_communities/utils.py
modules/weko-admin/weko_admin/models.py
modules/weko-admin/weko_admin/tasks.py
modules/weko-admin/weko_admin/utils.py
modules/weko-records/weko_records/api.py

フィードバックメール送信処理を修正しました。
主な修正点
- フィードバックメールに記載するアイテムがサブリポジトリごとになっていなかった点を修正
フィードバックレポートを送信した際に、別のサブリポジトリのアイテムも含まれていた。
フィルタが有効に働いていなかった。
- Root Indexの設定がオフの時に送信しない処理になっていなかった点を修正
サブリポジトリの送信除外対象者にRoot Indexの送信除外対象者が含まれていなかった。

フィードバックメール送信の修正

---

modules/weko-workflow/weko_workflow/api.py
modules/weko-workflow/weko_workflow/utils.py
modules/weko-workflow/weko_workflow/views.py

W-OA-IT-55
削除用ワークフローで「承認」のアクションがない場合、「END」アクションで「完了」ボタンを押さなければアクティビティが終了しない状態になってしまっているため、soft_delete時にアクティビティを終了させるよう修正。
W-OA-IT-64
削除用ワークフローで「承認」アクションがある時、削除ボタン押下後、「却下」をした場合に、前のアクションに戻って「作業中」で固定化されてしまう。前のアクションが「start」の場合に「作業中」になってしまうとアクティビティを終了することが出来ない状態になっている。
・「却下」された場合はprevious_actionメソッドに入る。ここで削除用の承認の「却下」だということを判断する。
・「却下」された場合は「END」を「作業済」にしてアクティビティを終了させる。
・「承認」が複数ある場合は、「却下」された「承認」以外を「スキップ」の状態にする。
modules/weko-workflow/weko_workflow/api.py
アクティビティのhistoryを取得する際に、action_order順に取得されるよう修正した。
workflow_action_historyに登録した順序で画面に表示されてしまっていたため。

W-OA-IT-55,W-OA-IT-64

---

modules/weko-logging/weko_logging/activity_logger.py
modules/weko-logging/weko_logging/handler.py
modules/weko-logging/weko_logging/models.py
modules/weko-search-ui/weko_search_ui/utils.py
modules/weko-workflow/weko_workflow/headless/activity.py

SWORD APIのインポート処理でファイル追加のログを追加。
parent_idのロジックを一部変更。Jsonには登録できていたが、columnになかったので追加できるようにした

add audit logs for sword api and update parent id calc process

---

install.sh
modules/weko-authors/weko_authors/admin.py
modules/weko-authors/weko_authors/tasks.py
modules/weko-itemtypes-ui/weko_itemtypes_ui/admin.py
modules/weko-logging/weko_logging/activity_logger.py
modules/weko-logging/weko_logging/handler.py
modules/weko-logging/weko_logging/models.py
modules/weko-records-ui/weko_records_ui/external.py
modules/weko-records-ui/weko_records_ui/views.py
modules/weko-search-ui/weko_search_ui/admin.py
modules/weko-search-ui/weko_search_ui/tasks.py
modules/weko-search-ui/weko_search_ui/utils.py
postgresql/ddl/W-OA-user_activity_log.sql

監査ログのparent_idをlog_group_idに変更
IDがリクエスト単位でそれぞれ割り振られるよう修正

change parent_id to log_group_id for user activity logs

---

modules/weko-authors/tests/conftest.py
modules/weko-authors/tests/test_utils.py

weko_authors/utils.pyのcount_authorsの単体テストを修正
使用していたfixtureが変わって通らなくなっていたので元々使っていたfixtureを使用するようにした

fix unit test of count_authors

---

modules/weko-accounts/tests/conftest.py
modules/weko-accounts/tests/test_admin.py
modules/weko-accounts/tests/test_api.py
modules/weko-accounts/tests/test_views.py
modules/weko-accounts/weko_accounts/api.py
modules/weko-accounts/weko_accounts/rest.py

Coverage: 29% -> 83% (改修前: 92 %)
1 failed, 6 passed, 43 error -> 1 failed, 49 passed (改修前: 2 failed, 38 passed)

単体テスト修正（weko-accounts）

---

modules/weko-accounts/tests/test_views.py

generate_ams_login_url()の単体テストを新規作成
shib_sp_login()、confirm_user()の単体テストを修正

未病のアクセス制御に関する単体テスト修正
