modules/invenio-stats/invenio_stats/aggregations.py
modules/invenio-stats/invenio_stats/queries.py

置換したメソッドに関するテストで、正常に動作したことを確認済です。

replace deepcopy with pickle / invenio-stats

---

modules/invenio-records-rest/invenio_records_rest/serializers/base.py
modules/invenio-records-rest/invenio_records_rest/serializers/jsonld.py
modules/invenio-records-rest/invenio_records_rest/sorter.py
modules/invenio-records-rest/invenio_records_rest/views.py

置換したメソッドに関するテストで、置換前と同じ結果となったことを確認済です。

replace deepcopy with pickle / invenio-records-rest

---

modules/weko-index-tree/sonar-project.properties
modules/weko-index-tree/weko_index_tree/api.py

置換したメソッドに関する既存のテストで、置換前と同じ結果となったことを確認済です。

replace deepcopy with pickle / weko-index-tree

---

modules/weko-workflow/weko_workflow/views.py

previous_actionレビュー用プルリクエスト
レビュー対象はprevious_actionですが、cancel_action、next_actionのpydocも記述してあります。

add pydoc in weko_workflow.views

---

modules/weko-workflow/weko_workflow/schema/marshmallow.py
modules/weko-workflow/weko_workflow/views.py

add refactoring code of views.py

add refactoring code of views.py

---

modules/weko-workflow/tests/conftest.py
modules/weko-workflow/tests/test_views.py

レヴュー依頼　リファクタリング後のテストコード
テスト対象メソッド：unlock_activity, check_approval, get_feedback_maillist, save_activity
test_views.pyとconftest.pyに追記しました

add after-refactoring test code

---

modules/weko-items-ui/weko_items_ui/static/js/weko_items_ui/feedback_maillist.js
modules/weko-workflow/weko_workflow/views.py

リファクタリングの修正
・save_activityのtry文
・Responseの形式を他と合わせた
・ステータスコード500を400に修正
・ValueError as errの使われていないerrを削除

fix refactoring code

---

modules/weko-admin/weko_admin/api.py
modules/weko-admin/weko_admin/templates/weko_admin/email_templates/site_license_report.html
modules/weko-admin/weko_admin/utils.py
modules/weko-admin/weko_admin/views.py
modules/weko-records/weko_records/serializers/utils.py
modules/weko-records/weko_records/serializers/wekolog.py
modules/weko-search-ui/weko_search_ui/config.py
modules/weko-search-ui/weko_search_ui/query.py
modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
modules/weko-theme/weko_theme/static/js/weko_theme/top_page.js

2.TOCメール送信を実現する機能
3.サイトライセンス機能の拡張 メール対応分
5.検索機能の改修

H2022-02 UMS連携

---

modules/weko-accounts/tests/test_api.py
modules/weko-accounts/tox.ini
modules/weko-accounts/weko_accounts/api.py
modules/weko-user-profiles/tests/conftest.py
modules/weko-user-profiles/tests/test_views.py
modules/weko-user-profiles/tox.ini

H2022-02 4. UMS連携機能 単体テスト

---

modules/weko-records/weko_records/serializers/utils.py
modules/weko-search-ui/weko_search_ui/config.py
modules/weko-search-ui/weko_search_ui/query.py

結合テストの不具合の修正を行いました。
対応した箇所は、結合テストの不具合管理表に記載されている以下の管理番号となります。
・H2022-01-003
・H2022-01-008
・H2022-01-009
・H2022-01-011

結合テストの不具合修正

---

modules/invenio-stats/invenio_stats/utils.py

H2022-02 IT 不具合修正

---

modules/weko-records-ui/weko_records_ui/static/js/weko_records_ui/detail.js

以下を修正
4/21 
利用規約のみの動作確認をしたところ、
利用規約に承諾し、[次へ]ボタンを押してもダイアログが閉じない

#36595 利用規約が閉じない

---

modules/weko-records-ui/tests/test_rest.py
modules/weko-records-ui/weko_records_ui/rest.py

bug fix in weko_records_ui/rest.py

bug fix in weko_records_ui/rest.py

---

modules/weko-workflow/tests/conftest.py
modules/weko-workflow/tests/test_api.py
modules/weko-workflow/tests/test_rest.py
modules/weko-workflow/tests/test_utils.py
modules/weko-workflow/weko_workflow/rest.py

@asuzuki1 
テストの作成が完了しましたので、ご確認お願いいたします。
※多言語対応の単体テストは実施が難しいため結合テストにまわしています
※モジュール全体のテストは現在実施中です

アクティビティ一覧取得API テスト作成

---

modules/weko-records-ui/tests/conftest.py
modules/weko-records-ui/tests/data/need_restricted_access_records_metadata.json
modules/weko-records-ui/tests/helpers.py
modules/weko-records-ui/tests/test_rest.py
modules/weko-records-ui/weko_records_ui/rest.py

ワークフローが完了していない場合はエラーとする処理を追加してある。

W2023-21 利用申請が必要かどうかを判断するAPI 単体テスト作成

---

modules/weko-records-ui/setup.py
modules/weko-records-ui/tests/test_rest.py
modules/weko-records-ui/weko_records_ui/config.py
modules/weko-records-ui/weko_records_ui/rest.py
modules/weko-records-ui/weko_records_ui/scopes.py
modules/weko-records-ui/weko_records_ui/utils.py
modules/weko-workflow/tests/test_rest.py
modules/weko-workflow/weko_workflow/config.py
modules/weko-workflow/weko_workflow/rest.py
modules/weko-workflow/weko_workflow/utils.py

アクティビティ一覧のURL修正
LimitRate対応
バージョン文字列変更(v1に変更)
OAuth2のスコープ対応
その他
HTTPgetでコンテンツタイプは不要なので削除

W2023-21 PG修正(URL修正/LimitRateの設定/バージョン文字列変更)

---

modules/weko-workflow/weko_workflow/rest.py

結合テスト不具合(W2023-21-032)修正
get_activity_display_infoの引数が増えていたので、使用している箇所すべてに対応

W2023-21 結合テスト不具合修正

---

modules/weko-records-ui/weko_records_ui/permissions.py
modules/weko-records-ui/weko_records_ui/static/js/weko_records_ui/detail.js
modules/weko-workflow/weko_workflow/templates/weko_workflow/admin/flow_detail.html
postgresql/ddl/W2023-22 mail_template_genre.sql
tools/updateRestrictedRecords.py
tools/upgradeW2023-22.sh

・records_metadata内にownersをkeyに持つ値の追加。
・adminsettings内に'secret_URL_filedownload'をkeyとする値を追加
・「オープンアクセス日：未来日」かつ、アイテムの公開日が本日以前の場合に、オープンアクセス日にかからわずファイルのDLを行えないように修正
・「プロパティアクセス：ログインユーザーのみ」かつ、「アクセスロール：未ログインユーザー」の場合に、管理者と登録者以外のDLを行えるように修正
・「プロパティアクセス：ログインユーザーのみ」のファイルに、一般ユーザーがDLを行う場合、DLを行えるように修正
・その他軽微な修正

upgrade対応テストにおける修正

---

modules/weko-items-ui/weko_items_ui/static/js/weko_items_ui/app.js
modules/weko-records-ui/weko_records_ui/fd.py
modules/weko-workflow/weko_workflow/views.py

プロパティアクセス：ログインユーザーのみ　に指定した際のロールのリストから「未ログインユーザー」を削除

プロパティアクセス：ログインユーザーのみ　に指定した際のロールのリスト変更

---

modules/weko-workflow/weko_workflow/admin.py
modules/weko-workflow/weko_workflow/static/js/weko_workflow/admin/flow_detail.js
modules/weko-workflow/weko_workflow/templates/weko_workflow/admin/flow_detail.html
modules/weko-workflow/weko_workflow/views.py

W2023 23 for merge(1) test

---

modules/invenio-stats/invenio_stats/utils.py
modules/invenio-stats/invenio_stats/utils_search.py
modules/weko-records-ui/weko_records_ui/fd.py
modules/weko-records/weko_records/serializers/utils.py
modules/weko-search-ui/weko_search_ui/config.py
modules/weko-search-ui/weko_search_ui/query.py

H2022-02(結合テストの改修)を広場環境にマージしました

Integration test bug fix

---

modules/weko-records-ui/requirements.txt
modules/weko-workflow/requirements.txt
modules/weko-workflow/weko_workflow/models.py
modules/weko-workflow/weko_workflow/views.py

・マージ時にRequestMailListクラスが2つになっていたのを修正
・get_activity_request_mailメソッドが使用されていた部分で一部get_activity_requestmailメソッドになっていたのを修正
・その他requirements.txtに新しいモジュールの追加

マージの修正その他です。

---

modules/weko-search-ui/weko_search_ui/utils.py

マージ時に引数名が変更されましたのでそれに対応させました。

---

modules/weko-records/weko_records/api.py

ミスで削除したメソッドを戻します。
def get_request_mail_by_mailaddress(cls, address)

ミスで削除したメソッドを戻します。

---

modules/invenio-records-rest/invenio_records_rest/serializers/json.py
modules/weko-records-ui/tests/test_utils.py
modules/weko-records-ui/weko_records_ui/utils.py
modules/weko-search-ui/tests/test_query.py
modules/weko-search-ui/weko_search_ui/query.py

OpenSearchAPIの不具合の修正を行いました。
- `replace_license_free_for_opensearch`　
- ライセンスの変更処理に使用した関数です。
- 既存の関数、`replace_license_free`がElasticsearchの検索結果に対応していなかったため作成しました。

日付検索、license_freeの出力 修正

---

modules/weko-items-ui/setup.py
modules/weko-items-ui/weko_items_ui/bundles.py
modules/weko-items-ui/weko_items_ui/static/js/weko_items_ui/app.js
modules/weko-items-ui/weko_items_ui/static/js/weko_items_ui/no_file_approval.js
modules/weko-items-ui/weko_items_ui/templates/weko_items_ui/iframe/item_edit.html
modules/weko-records/weko_records/api.py
modules/weko-records/weko_records/models.py
modules/weko-workflow/weko_workflow/api.py
modules/weko-workflow/weko_workflow/models.py
modules/weko-workflow/weko_workflow/schema/marshmallow.py
modules/weko-workflow/weko_workflow/utils.py
modules/weko-workflow/weko_workflow/views.py
postgresql/ddl/W2023-23-item_application.sql

W2023 23 4 

---

modules/weko-items-ui/weko_items_ui/static/js/weko_items_ui/app.js
modules/weko-items-ui/weko_items_ui/static/js/weko_items_ui/no_file_approval.js
modules/weko-items-ui/weko_items_ui/static/js/weko_items_ui/request_maillist.js
modules/weko-records/weko_records/api.py
modules/weko-workflow/weko_workflow/views.py

upgrade for "term_free"

---

modules/weko-admin/weko_admin/admin.py
modules/weko-admin/weko_admin/static/js/weko_admin/sword_api_settings.js
modules/weko-admin/weko_admin/templates/weko_admin/admin/sword_api_settings.html

削除済みアイテムタイプ判定処理修正
weko_admin/admin.py
sword_api_settings.js
sword_api_settings.html

w2023-41　fix/deleted_itemtype

---

modules/weko-records-ui/weko_records_ui/views.py
modules/weko-search-ui/tests/test_views.py
modules/weko-search-ui/weko_search_ui/views.py
modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
modules/weko-theme/weko_theme/static/js/weko_theme/top_page.js
modules/weko-theme/weko_theme/static/js/weko_theme/widget.js
modules/weko-theme/weko_theme/templates/weko_theme/body_search.html
modules/weko-theme/weko_theme/templates/weko_theme/body_search_detail_new.html
modules/weko-theme/weko_theme/utils.py

改修箇所
- render_templateで渡されている、detail_conditionの処理をコメントアウト
- modules/weko-records-ui/weko_records_ui/views.py
- modules/weko-search-ui/weko_search_ui/views.py
- modules/weko-theme/weko_theme/utils.py
- detail_condition取得用のAPIを追加
- modules/weko-search-ui/weko_search_ui/views.py
- APIで取得したdetail_conditionを使用する処理に変更
- modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
- templateもJSに合わせた処理に変更
- modules/weko-theme/weko_theme/templates/weko_theme/body_search.html
- modules/weko-theme/weko_theme/templates/weko_theme/body_search_detail_new.html

パフォーマンス改善/詳細検索機能/APIを使用する形に改修

---

modules/invenio-stats/invenio_stats/config.py
modules/invenio-stats/invenio_stats/contrib/registrations.py
modules/invenio-stats/invenio_stats/utils.py
modules/invenio-stats/tests/test_utils.py
modules/weko-gridlayout/tests/test_views.py
modules/weko-gridlayout/weko_gridlayout/views.py

アクセスカウンター表示に関する改修を行いました。
改修内容
- キーと値を追加
- modules/invenio-stats/invenio_stats/config.py
- 作成したキーで使用するための辞書を追加
- modules/invenio-stats/invenio_stats/contrib/registrations.py
- アクセスカウンター専用のクラスを追加
- modules/invenio-stats/invenio_stats/utils.py
- 新規作成したクラスを呼び出す処理に変更、カウント数の計算処理を削除
- modules/weko-gridlayout/weko_gridlayout/views.py

アクセスカウンター表示処理の改修

---

modules/weko-swordserver/tests/test_views.py
modules/weko-swordserver/weko_swordserver/views.py

fix oath scopes

---

modules/invenio-stats/invenio_stats/utils_search.py
modules/weko-admin/tests/conftest.py
modules/weko-admin/tests/test_admin.py
modules/weko-admin/tests/test_utils.py
modules/weko-admin/weko_admin/admin.py
modules/weko-admin/weko_admin/config.py
modules/weko-admin/weko_admin/static/js/weko_admin/stats_report.js
modules/weko-admin/weko_admin/utils.py
modules/weko-theme/weko_theme/utils.py

get_reports メソッド追加
get_files_stats_output メソッド修正
定型レポート js修正

NII_WEKO3-62 定型レポートのダウンロード処理の改善

---

modules/weko-accounts/tests/test_views.py
modules/weko-accounts/weko_accounts/templates/weko_accounts/login_user.html
modules/weko-accounts/weko_accounts/views.py
modules/weko-gridlayout/tests/test_views.py
modules/weko-gridlayout/weko_gridlayout/views.py
modules/weko-search-ui/weko_search_ui/views.py
modules/weko-theme/weko_theme/utils.py
nginx/login.php

NII_WEKO3-70 シボレスログイン後のリダイレクト対応

---

nginx/login.php
nginx/weko.conf

Add flag for not check `wekoSocietyAffiliation` on WEKO3 shib login.

HIROBA_MIG-1830 学会に所属しないUMSアカウントでWEKO3にログインできない

---

modules/weko-admin/tests/conftest.py
modules/weko-admin/tests/test_utils.py
modules/weko-admin/weko_admin/config.py
modules/weko-admin/weko_admin/utils.py

V0.9.26 hiroba sitelicense

---

modules/weko-search-ui/weko_search_ui/utils.py

(cherry picked from commit 3a149534dffd2804a824bdbf10f32947a5bf2428)
-----
https://nii.backlog.jp/view/HIROBA_MIG-1833

HIROBA_MIG-1833：weko#38306 auto fill file size

---

modules/invenio-records/requirements.txt
modules/invenio-records/requirements2.txt
modules/invenio-records/setup.cfg
modules/invenio-records/tests/conftest.py
modules/invenio-records/tests/test_alembic.py
modules/invenio-records/tests/test_api.py
modules/invenio-records/tests/test_api_dumpers.py
modules/invenio-records/tests/test_custom_db.py
modules/invenio-records/tests/test_encoder.py
modules/invenio-records/tests/test_field_model.py
modules/invenio-records/tests/test_invenio_records.py
modules/invenio-records/tests/test_relations_field.py
modules/invenio-records/tests/test_relations_modelfield.py
modules/invenio-records/tests/test_relations_systemfield.py
modules/invenio-records/tests/test_signals.py
modules/invenio-records/tests/test_systemfields.py
modules/invenio-records/tests/test_systemfields_relatedmodelfield.py
modules/invenio-records/tox.ini

```
---------- coverage: platform linux, python 3.12.6-final-0 -----------
Name                                                       Stmts   Miss Branch BrPart  Cover
--------------------------------------------------------------------------------------------
invenio_records/__init__.py                                    4      0      0      0   100%
invenio_records/admin.py                                      58     58     12      0     0%
invenio_records/api.py                                       235     11    116      7    95%
invenio_records/config.py                                      6      0      0      0   100%
invenio_records/dictutils.py                                  87      7     66      8    89%
invenio_records/dumpers/__init__.py                            3      0 …
```

fix: invenio-records test critical error to run tox

---

modules/invenio-files-rest/requirements.txt
modules/invenio-files-rest/requirements2.txt
modules/invenio-files-rest/setup.cfg
modules/invenio-files-rest/tests/conftest.py
modules/invenio-files-rest/tests/test_models.py
modules/invenio-files-rest/tests/test_signals.py
modules/invenio-files-rest/tests/test_views_bucket.py
modules/invenio-files-rest/tests/test_views_location.py
modules/invenio-files-rest/tests/test_views_multipart.py
modules/invenio-files-rest/tests/test_views_objectversion.py
modules/invenio-files-rest/tox.ini

```
---------- coverage: platform linux, python 3.12.6-final-0 -----------
Name                                     Stmts   Miss Branch BrPart  Cover
--------------------------------------------------------------------------
invenio_files_rest/__init__.py               4      0      0      0   100%
invenio_files_rest/admin.py                133     17     30      7    82%
invenio_files_rest/api.py                   21     14      4      0    28%
invenio_files_rest/app.py                    4      0      0      0   100%
invenio_files_rest/cli.py                   82     47     64      0    60%
invenio_files_rest/config.py                61      0      0      0   100%
invenio_files_rest/errors.py                64      4      2      1    92%
invenio_files_rest/ext.py                   57 …
```

fix: invenio-files-rest test critical error to run tox

---

modules/invenio-oauth2server/invenio_oauth2server/views/settings.py
modules/weko-groups/weko_groups/views.py
modules/weko-theme/weko_theme/templates/weko_theme/header_login.html
modules/weko-user-profiles/weko_user_profiles/views.py
scripts/instance.cfg

* Add menu visibility setting for profile, applications and groups

HIROBA_MIG-1876

---

modules/invenio-accounts/invenio_accounts/admin.py
modules/invenio-oaiserver/invenio_oaiserver/verbs.py

fix 46978, 46997

---

modules/invenio-records-rest/invenio_records_rest/sorter.py

[#375 再修正](https://redmine.devops.rcos.nii.ac.jp/issues/47939#note-22)

fix 47939-2

---

modules/weko-records-ui/tests/conftest.py
modules/weko-records-ui/tests/test_models.py
modules/weko-records-ui/tests/test_utils.py
modules/weko-records-ui/tests/test_views.py
modules/weko-records-ui/weko_records_ui/config.py
modules/weko-records-ui/weko_records_ui/fd.py
modules/weko-records-ui/weko_records_ui/models.py
modules/weko-records-ui/weko_records_ui/utils.py
modules/weko-records-ui/weko_records_ui/views.py
modules/weko-workflow/tests/test_utils.py
modules/weko-workflow/weko_workflow/utils.py

シークレットURL・ワンタイムURLの生成ロジック及びダウンロードロジックを変更しました。

W2024-23 | Change URL generation and download logic

---

modules/weko-records-ui/tests/conftest.py
modules/weko-records-ui/tests/test_fd.py
modules/weko-records-ui/tests/test_models.py
modules/weko-records-ui/tests/test_utils.py
modules/weko-records-ui/weko_records_ui/fd.py
modules/weko-records-ui/weko_records_ui/models.py
modules/weko-records-ui/weko_records_ui/utils.py

- ダウンロードログテーブル(file_url_download_log)のモデルクラス(FileUrlDownloadLog)を定義しました。
- ダウンロードログを保存する関数を定義しました。
- シークレットURL・ワンタイムURL利用時にダウンロードログが保存される処理を実装しました。

W2024-23 | Add download-log models and saving features

---

modules/weko-records-ui/tests/test_views.py
modules/weko-records-ui/weko_records_ui/config.py
modules/weko-records-ui/weko_records_ui/fd.py
modules/weko-records-ui/weko_records_ui/views.py

シークレットURL・ワンタイムURLへの削除エンドポイントを追加しました。

Add delete endpoint for download url

---

modules/weko-accounts/weko_accounts/static/css/weko_accounts/wayf_custom.css
modules/weko-accounts/weko_accounts/templates/weko_accounts/login_user.html

【W-OA-14】ログイン画面の更新

---

docker-compose.es-v7.yml
tools/reindex_all_index.py

[48929](https://redmine.devops.rcos.nii.ac.jp/issues/48929)

Update Migration Tool

---

docker-compose.es-v7.yml
tools/reindex_es7_to_os.py

[48929](https://redmine.devops.rcos.nii.ac.jp/issues/48929)

Reindex tool for es7 to os

---

modules/weko-records-ui/weko_records_ui/external.py

configから値を取得する際のキーの誤りを修正

---

modules/weko-search-ui/tests/conftest.py
modules/weko-search-ui/tests/data/list_records/list_records_authors.json
modules/weko-search-ui/tests/data/list_records/list_records_authors_error.json
modules/weko-search-ui/tests/test_utils.py

Develop w oa 15 3.1.4 UT test

---

modules/weko-items-ui/weko_items_ui/utils.py

バグNo18, 23の対応

---

modules/weko-workspace/weko_workspace/static/js/WorkspaceItemList.js
modules/weko-workspace/weko_workspace/views.py

@asuzuki1 
Web Container エラー修正と Intergerの修正を行いました。
ご確認お願い致します。

CheckBox,Interger修正

---

modules/weko-items-ui/weko_items_ui/utils.py

バグNo23の修正対応

---

modules/weko-workspace/weko_workspace/templates/weko_workspace/workspace_base.html

・言語切り替えの実働確認済み
ワークスペース画面でEnglish→日本語にして画面が更新され、トップページで日本語表記になっていることを確認
日本語→Englishについても同様
ただし、ワークスペース画面は日本語化されなかったため別個のバグがあると思われる

fix W-OA-04-004

---

modules/weko-search-ui/weko_search_ui/utils.py
modules/weko-workflow/weko_workflow/headless/activity.py

* SWORD APIでワークフロー経由でアイテム登録時、アイテムリンクが作成できなかった問題を修正
* SWORD APIでワークフロー経由でアイテム登録時、アイテムリンク先のタイトルが表示できなかった問題を修正

Fix W-OA-IT-071

---

modules/invenio-oauth2server/invenio_oauth2server/models.py
modules/weko-admin/weko_admin/admin.py
modules/weko-admin/weko_admin/static/js/weko_admin/jsonld_mapping_setting.js
modules/weko-admin/weko_admin/static/js/weko_admin/sword_api_jsonld_setting.js
modules/weko-admin/weko_admin/templates/weko_admin/admin/jsonld_mapping_settings.html
modules/weko-admin/weko_admin/templates/weko_admin/admin/sword_api_jsonld_settings.html
modules/weko-records-ui/weko_records_ui/permissions.py
modules/weko-records-ui/weko_records_ui/views.py
modules/weko-swordserver/weko_swordserver/api.py
modules/weko-workflow/weko_workflow/api.py

W-OA-IT-054
W-OA-IT-092
W-OA-IT-097
W-OA-IT-099
W-OA-IT-100

Fix / SWORD setting and item deletion

---

modules/weko-accounts/weko_accounts/api.py
modules/weko-authors/weko_authors/admin.py
modules/weko-authors/weko_authors/api.py
modules/weko-authors/weko_authors/rest.py
modules/weko-authors/weko_authors/tasks.py
modules/weko-authors/weko_authors/utils.py
modules/weko-authors/weko_authors/views.py

Add logger for weko-authors

---

modules/weko-records/weko_records/utils.py
modules/weko-search-ui/weko_search_ui/static/templates/weko_search_ui/itemlist.html

fix display creator in itemlist

---

modules/weko-swordserver/weko_swordserver/utils.py

fix: error status and add check

---

modules/weko-search-ui/weko_search_ui/mapper.py

fix: mapping condition

---

modules/weko-deposit/weko_deposit/api.py
modules/weko-search-ui/weko_search_ui/mapper.py
modules/weko-swordserver/weko_swordserver/views.py
modules/weko-workflow/weko_workflow/headless/activity.py

update: support item upgrade via headless activity

---

modules/weko-index-tree/tests/test_schema.py
modules/weko-index-tree/weko_index_tree/rest.py
modules/weko-index-tree/weko_index_tree/schema.py

W-OA-IT-139
W-OA-IT-140
W-OA-IT-141
W-OA-IT-143
W-OA-IT-144

Fix / index api create

---

modules/weko-workspace/weko_workspace/config.py
modules/weko-workspace/weko_workspace/utils.py
modules/weko-workspace/weko_workspace/views.py

Fix logic for get items in workspace
W-OA-019
W-OA-023
W-OA-038
W-OA-057
W-OA-082

Fix W-OA-IT-019 and more

---

modules/weko-workspace/weko_workspace/views.py

Fix W-OA-IT-189

---

modules/weko-swordserver/weko_swordserver/utils.py
modules/weko-workflow/weko_workflow/headless/activity.py

Fix / check workflow deleted or not

---

modules/weko-items-ui/weko_items_ui/utils.py
modules/weko-items-ui/weko_items_ui/views.py
modules/weko-swordserver/weko_swordserver/utils.py

Fix / not to use deleted workflow.

---

modules/weko-search-ui/weko_search_ui/mapper.py
modules/weko-workflow/weko_workflow/headless/activity.py

* SWORD API使用時、wk:feedbackMailに複数入力しても1個しか反映されない不具合を修正
* SWORD API使用時、wk:requestMailに入力した値をアイテムに反映する実装を追加

fix w-oa-it-173

---

modules/weko-workflow/weko_workflow/admin.py
modules/weko-workflow/weko_workflow/templates/weko_workflow/admin/workspace_workflow_setting.html

fix workspace_workflow_setting

---

modules/weko-items-ui/weko_items_ui/utils.py
modules/weko-workflow/weko_workflow/api.py

* 削除アクティビティの所有者を削除承認完了メールの送信対象者に追加。
* 承認が複数回あるフローに対応。
* ログを修正

fix mail notify

---

modules/weko-items-ui/weko_items_ui/views.py
modules/weko-search-ui/weko_search_ui/utils.py
modules/weko-swordserver/weko_swordserver/utils.py
modules/weko-swordserver/weko_swordserver/views.py
modules/weko-workflow/weko_workflow/api.py
modules/weko-workflow/weko_workflow/headless/activity.py

Fix / check item status before delete.

---

modules/weko-records-ui/weko_records_ui/views.py
modules/weko-swordserver/weko_swordserver/utils.py
modules/weko-workflow/weko_workflow/api.py
modules/weko-workflow/weko_workflow/utils.py
modules/weko-workflow/weko_workflow/views.py

Update / deletion rejected notification. 

---

modules/weko-items-ui/weko_items_ui/utils.py
modules/weko-search-ui/weko_search_ui/utils.py
modules/weko-swordserver/weko_swordserver/views.py
modules/weko-workflow/weko_workflow/api.py
modules/weko-workflow/weko_workflow/utils.py

Fix / no files content extract

---

modules/weko-items-ui/weko_items_ui/config.py
modules/weko-items-ui/weko_items_ui/utils.py
modules/weko-items-ui/weko_items_ui/views.py
modules/weko-records-ui/weko_records_ui/config.py
modules/weko-records-ui/weko_records_ui/external.py
modules/weko-workspace/weko_workspace/config.py
modules/weko-workspace/weko_workspace/static/js/weko_workspace/workspace_register.js
modules/weko-workspace/weko_workspace/utils.py
modules/weko-workspace/weko_workspace/views.py
scripts/instance.cfg

W oa it 284

---

modules/weko-index-tree/weko_index_tree/config.py
modules/weko-indextree-journal/weko_indextree_journal/config.py

weko-index-treeおよびweko-indextree-journalモジュールのconfig.pyからIID削除

delete iid config

---

modules/weko-logging/weko_logging/audit.py

監査ログの初期化処理で、追加されたハンドラを一度すべて削除するように変更。

change method of adding audit log handler

---

modules/weko-items-ui/weko_items_ui/utils.py
modules/weko-items-ui/weko_items_ui/views.py
modules/weko-search-ui/weko_search_ui/admin.py
modules/weko-workflow/weko_workflow/headless/activity.py

Fix / save activity tempdata when failed to validate matadata.

---

modules/weko-items-ui/weko_items_ui/static/js/weko_items_ui/app.js
modules/weko-items-ui/weko_items_ui/utils.py
modules/weko-items-ui/weko_items_ui/views.py
modules/weko-search-ui/weko_search_ui/utils.py
modules/weko-swordserver/weko_swordserver/views.py

exclude itemself when check duplicate

---

modules/weko-workflow/weko_workflow/api.py

jsonのdumpsを呼び出す際に、UUIDが含まれているためdefault引数を設定、strを呼び出し文字列型に変換する処理を追加

add default to json dump

---

modules/weko-search-ui/tests/test_mapper.py
modules/weko-search-ui/weko_search_ui/mapper.py

Fix / file entities id in ro-crate.

---

modules/weko-search-ui/tests/data/jsonld/ro-crate-metadata.json
modules/weko-search-ui/tests/data/jsonld/ro-crate-metadata2.json
modules/weko-search-ui/tests/data/jsonld/ro-crate_mapping.json
modules/weko-search-ui/tests/test_mapper.py
modules/weko-search-ui/weko_search_ui/mapper.py
modules/weko-search-ui/weko_search_ui/utils.py

`item_30001_file22 -> url -> url` is now able to map. 
W-OA-IT-043
W-OA-IT-320

Fix / allow repeated property names.

---

modules/weko-logging/weko_logging/utils.py

fix export log zip file format

---

modules/weko-workspace/weko_workspace/api.py

fix W-OA-IT-319

---

modules/weko-items-autofill/weko_items_autofill/utils.py
modules/weko-items-autofill/weko_items_autofill/views.py
modules/weko-items-ui/weko_items_ui/utils.py
modules/weko-workspace/weko_workspace/config.py
modules/weko-workspace/weko_workspace/static/js/weko_workspace/WorkspaceItemList.js
modules/weko-workspace/weko_workspace/utils.py

use cache at metadata fill
fix check_duplicate
fix docstring
fix DOI link

Modified use cache at metadata fill , and more

---

modules/weko-workspace/weko_workspace/static/css/weko_workspace/style.css
modules/weko-workspace/weko_workspace/static/js/weko_workspace/workspace_register.js
modules/weko-workspace/weko_workspace/templates/weko_workspace/item_register.html
modules/weko-workspace/weko_workspace/views.py

Fix workspace for issue #53400

---

nginx/ams/weko-frontend/pages/ams/detail.vue

未病8 GRDMへのリンク 修正

---

nginx/ams/weko-frontend/app.config.ts
nginx/ams/weko-frontend/pages/ams/detail.vue
nginx/ams/weko-frontend/pages/ams/login.vue

* フロントのembedded dsで使用する値をapp.config.tsに移動
* プロジェクトURLかどうか判定用の値をapp.config.tsに移動
*  grdmのURLを設定した場合はURLがこの値から始まるかどうかで絞り込みを行う

Move configuration values to a configuration file.

---

modules/weko-search-ui/tests/test_mapper.py
modules/weko-search-ui/weko_search_ui/mapper.py

Fix schema handling for export extra metadata.

---

modules/weko-search-ui/tests/test_mapper.py
modules/weko-search-ui/weko_search_ui/mapper.py

Fix detached Instance for xml import.

---

modules/weko-items-ui/tests/test_utils.py
modules/weko-items-ui/weko_items_ui/utils.py

Fixed duplicate detection process

---

modules/weko-items-ui/weko_items_ui/utils.py
modules/weko-user-profiles/weko_user_profiles/forms.py
modules/weko-user-profiles/weko_user_profiles/models.py
modules/weko-user-profiles/weko_user_profiles/utils.py

ユーザープロフィール機能で、初期設定が読み込まれていない箇所にデータを追加。

Fix user profile initial settings
